package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	_ "fmt"
	"github.com/xcheng85/simple-graphql-go/graph/model"
)

// GetAllPlayers is the resolver for the GetAllPlayers field.
func (r *queryResolver) GetAllPlayers(ctx context.Context) ([]*model.Player, error) {
	players := []*model.Player{
		{
			ID: "atp-0",
			First: "Roger",
			Last: "Federer",
			Country: &model.Country{
				ID: "contry-0",
				Name: "Swiss",
			},
		},
	}
	return players, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
