package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"strconv"
	"github.com/xcheng85/simple-graphql-go/graph/model"
)

// AddPlayer is the resolver for the addPlayer field.
func (r *mutationResolver) AddPlayer(ctx context.Context, player model.PlayerInput) (*model.Player, error) {
	numPlayers := len(r.playersMap)
	//playerId := fmt.Sprintf("%d", numPlayers);
	playerId := strconv.Itoa(numPlayers)
	p := &model.Player{
		ID:      playerId,
		First:   player.First,
		Last:    player.Last,
		Country: player.Country,
		Gender:  player.Gender,
	}
	r.playersMap[playerId] = p
	return p, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]*model.Player, error) {
	players := make([]*model.Player, len(r.playersMap))
	idx := 0
	for _, p := range r.playersMap {
		players[idx] = p
	}
	return players, nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id string) (*model.Player, error) {
	p:= r.playersMap[id]
	return p, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func (r *mutationResolver) CreatePlayer(ctx context.Context, player model.PlayerInput) (*model.Player, error) {
	numPlayers := len(r.playersMap)
	//playerId := fmt.Sprintf("%d", numPlayers);
	playerId := strconv.Itoa(numPlayers)
	p := &model.Player{
		ID:      playerId,
		First:   player.First,
		Last:    player.Last,
		Country: player.Country,
		Gender:  player.Gender,
	}
	r.playersMap[playerId] = p
	return p, nil
}
func NewResolver() Config {
	r := Resolver{}
	r.playersMap = make(map[string]*model.Player)
	return Config{
		Resolvers: &r,
	}
}
