// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	ID   string `json:"id"`
	Name string `json:"Name"`
}

type Player struct {
	ID      string   `json:"id"`
	First   string   `json:"First"`
	Last    string   `json:"Last"`
	Country *Country `json:"Country"`
}
